title: 'AirWare'
email: 'your-email@example.com'
description: >- # this means to ignore newlines until "baseurl:"
  Say something to the world.
  Make a website and start publishing your content online in less than 5 minutes, for free.
baseurl: "/AirWare" # the subpath of your site, e.g. /blog
url: "https://kierancondon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kierancondon
github_username:  kierancondon

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Tipue search settings
tipue_search:
  include:
    pages: true
    posts: true
#  exclude:
#    files: [search.html]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
